from pipelines.taxirio.cities import *
from pipelines.taxirio.cities_staging import *
from pipelines.taxirio.discounts import *
from pipelines.taxirio.discounts_staging import *
from pipelines.taxirio.drivers import *
from pipelines.taxirio.drivers_staging import *
from pipelines.taxirio.passengers import *
from pipelines.taxirio.passengers_staging import *
from pipelines.taxirio.paymentmethods import *
from pipelines.taxirio.paymentmethods_staging import *
from pipelines.taxirio.races import *
from pipelines.taxirio.races_staging import *
from pipelines.taxirio.rankingraces import *
from pipelines.taxirio.rankingraces_staging import *
from pipelines.taxirio.users import *
from pipelines.taxirio.users_staging import *
