SELECT
    CAST(iddata AS INT64) AS iddata,
    CAST(data AS DATE) AS data,
    CAST(data_inicio_semana AS DATE) AS data_inicio_semana,
    CAST(data_fim_semana AS DATE) AS data_fim_semana,
    CAST(numero_dia_semana AS INT64) AS numero_dia_semana,
    CAST(nome_dia_semana AS STRING) AS nome_dia_semana,
    CAST(numero_dia_mes AS INT64) AS numero_dia_mes,
    CAST(idsemana AS INT64) AS idsemana,
    CAST(numero_semana_no_mes AS INT64) AS numero_semana_no_mes,
    CAST(numero_semana_no_ano AS INT64) AS numero_semana_no_ano,
    CAST(nome_semana_no_mes AS STRING) AS nome_semana_no_mes,
    CAST(nome_semana_no_ano AS STRING) AS nome_semana_no_ano,
    CAST(idquinzena AS INT64) AS idquinzena,
    CAST(numero_quinzena AS INT64) AS numero_quinzena,
    CAST(nome_quinzena AS STRING) AS nome_quinzena,
    CAST(nome_quinzena_ano AS STRING) AS nome_quinzena_no_ano,
    CAST(idmes AS INT64) AS idmes,
    CAST(numero_mes AS INT64) AS numero_mes,
    CAST(nome_mes AS STRING) AS nome_mes,
    CAST(idtrimestre AS INT64) AS idtrimestre,
    CAST(nome_trimestre AS STRING) AS nome_trimestre,
    CAST(idsemestre AS INT64) AS idsemestre,
    CAST(nome_semestre AS STRING) AS nome_semestre,
    CAST(idano AS INT64) AS idano,
    CAST(nome_ano AS INT64) AS nome_ano,
    CAST(iddia_util AS INT64) AS iddia_util,
    CAST(desc_dia_util AS STRING) AS desc_dia_util
FROM
    `rj-iplanrio.adm_processo_interno_processorio_staging.dim_data`
